## 1. Import Data

In [4]:
import pandas as pd
pd.set_option('display.max_columns', 500)

## 2. Read Datasets using Pandas

In [6]:
data = pd.read_csv("../train_ver2.csv")

/Library/Python/2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## 3. Sort By ncodepers (Customer Code)

In [7]:
sorted_data = data.sort(['ncodpers','fecha_dato'],ascending=[True,True])
sorted_data

/Library/Python/2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,ult_fec_cli_1t,indrel_1mes,tiprel_1mes,indresi,indext,conyuemp,canal_entrada,indfall,tipodom,cod_prov,nomprov,ind_actividad_cliente,renta,segmento,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,ind_deme_fin_ult1,ind_dela_fin_ult1,ind_ecue_fin_ult1,ind_fond_fin_ult1,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
416965,2015-01-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
836224,2015-02-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
1673961,2015-03-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
1882060,2015-04-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
3144382,2015-05-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
3565837,2015-06-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
4078996,2015-07-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
5319234,2015-08-28,15889,F,ES,V,56,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
5705188,2015-09-28,15889,F,ES,V,56,1995-01-16,0.0,247,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
6973298,2015-10-28,15889,F,ES,V,56,1995-01-16,0.0,248,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
7450451,2015-11-28,15889,F,ES,V,56,1995-01-16,0.0,249,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
8617992,2015-12-28,15889,F,ES,V,56,1995-01-16,0.0,250,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
9401570,2016-01-28,15889,F,ES,V,56,1995-01-16,0.0,251,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
10426092,2016-02-28,15889,F,ES,V,56,1995-01-16,0.0,252,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
11170871,2016-03-28,15889,F,ES,V,56,1995-01-16,0.0,253,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
12221013,2016-04-28,15889,F,ES,V,56,1995-01-16,0.0,254,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
13026343,2016-05-28,15889,F,ES,V,56,1995-01-16,0.0,255,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.9,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
416966,2015-01-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
836223,2015-02-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
1673960,2015-03-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
2092183,2015-04-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
3144383,2015-05-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
3565760,2015-06-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
4078995,2015-07-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
5319233,2015-08-28,15890,A,ES,V,62,1995-01-16,0.0,247,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
5705187,2015-09-28,15890,A,ES,V,62,1995-01-16,0.0,248,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
6909778,2015-10-28,15890,A,ES,V,63,1995-01-16,0.0,249,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
7450450,2015-11-28,15890,A,ES,V,63,1995-01-16,0.0,250,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
8617993,2015-12-28,15890,A,ES,V,63,1995-01-16,0.0,251,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
9401569,2016-01-28,15890,A,ES,V,63,1995-01-16,0.0,252,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.2,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13336786,2016-05-28,1553654,N,ES,H,29,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,30.0,MURCIA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336797,2016-05-28,1553655,N,ES,H,21,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,41.0,SEVILLA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336811,2016-05-28,1553656,N,ES,V,38,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,S,NaN,NaN,N,1.0,7.0,"BALEARS, ILLES",0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336812,2016-05-28,1553657,N,ES,H,32,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,2.0,ALBACETE,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336813,2016-05-28,1553658,N,ES,V,28,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336838,2016-05-28,1553660,N,ES,V,50,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,52.0,MELILLA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336837,2016-05-28,1553661,N,ES,H,40,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336836,2016-05-28,1553662,N,ES,H,65,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,29.0,MALAGA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336835,2016-05-28,1553663,N,ES,V,52,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,26.0,"RIOJA, LA",0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336834,2016-05-28,1553664,N,ES,H,29,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336833,2016-05-28,1553665,N,ES,V,20,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,12.0,CASTELLON,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336832,2016-05-28,1553667,N,ES,H,35,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,S,NaN,NaN,N,1.0,8.0,BARCELONA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336831,2016-05-28,1553668,N,ES,V,26,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,33.0,ASTURIAS,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336830,2016-05-28,1553669,N,ES,H,34,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,18.0,GRANADA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336829,2016-05-28,1553670,N,ES,H,21,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336828,2016-05-28,1553672,N,ES,V,20,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,44.0,TERUEL,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336827,2016-05-28,1553673,N,ES,V,28,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336826,2016-05-28,1553675,N,ES,H,56,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,S,NaN,NaN,N,1.0,48.0,BIZKAIA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336825,2016-05-28,1553676,N,ES,V,32,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336824,2016-05-28,1553677,N,ES,V,27,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336823,2016-05-28,1553679,N,ES,V,28,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,45.0,TOLEDO,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336822,2016-05-28,1553680,N,ES,V,39,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,38.0,SANTA CRUZ DE TENERIFE,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336821,2016-05-28,1553681,N,ES,V,37,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,24.0,LEON,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336820,2016-05-28,1553683,N,ES,H,43,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336819,2016-05-28,1553684,N,ES,H,86,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336818,2016-05-28,1553685,N,ES,V,52,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,13.0,CIUDAD REAL,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336817,2016-05-28,1553686,N,ES,H,30,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,S,NaN,NaN,N,1.0,41.0,SEVILLA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336816,2016-05-28,1553687,N,ES,V,21,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,28.0,MADRID,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336815,2016-05-28,1553688,N,ES,H,43,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,39.0,CANTABRIA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13336814,2016-05-28,1553689,N,ES,V,40,2016-05-31,1.0,0,1.0,NaN,NaN,NaN,S,N,NaN,NaN,N,1.0,21.0,HUELVA,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0

In [105]:
filtered_sorted_data = sorted_data.head(10000)

## Export To CSV

In [106]:
filtered_sorted_data.to_csv("filtered_data_mining.csv", index=False)

In [107]:
str = "Date	Customer_Code	Employee_index	Country_residence	sex	age	Date_Registered	New_customer_Index	seniority	Primary	Last_date_primary	type	relation_type	Residence_index	Foreigner_index	Spouse_index	channel_join	Deceased_index	Primary_Addr	Province_code	Province_name	Activity_index	Gross_income	Segmentation	Saving_Account	Guarantees	Current_Accounts	Derivada_Account	Payroll_Account	Junior_Account	Mas_particular_Account	particular_Account	Plus_Account	Shortterm_deposits	Mediumterm_deposits	Longterm_deposits	eaccount	Funds	Mortgage	Pensions	Loans	Taxes	Credit_Card	Securities	Home_Account	Payroll	Pensions	Direct_Debit"
columns = str.split("\t");

filtered_sorted_data.columns = columns
filtered_sorted_data

,Date,Customer_Code,Employee_index,Country_residence,sex,age,Date_Registered,New_customer_Index,seniority,Primary,Last_date_primary,type,relation_type,Residence_index,Foreigner_index,Spouse_index,channel_join,Deceased_index,Primary_Addr,Province_code,Province_name,Activity_index,Gross_income,Segmentation,Saving_Account,Guarantees,Current_Accounts,Derivada_Account,Payroll_Account,Junior_Account,Mas_particular_Account,particular_Account,Plus_Account,Shortterm_deposits,Mediumterm_deposits,Longterm_deposits,eaccount,Funds,Mortgage,Pensions,Loans,Taxes,Credit_Card,Securities,Home_Account,Payroll,Pensions,Direct_Debit
416965,2015-01-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
836224,2015-02-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
1673961,2015-03-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
1882060,2015-04-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
3144382,2015-05-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
3565837,2015-06-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
4078996,2015-07-28,15889,F,ES,V,56,1995-01-16,0.0,245,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
5319234,2015-08-28,15889,F,ES,V,56,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
5705188,2015-09-28,15889,F,ES,V,56,1995-01-16,0.0,247,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
6973298,2015-10-28,15889,F,ES,V,56,1995-01-16,0.0,248,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
7450451,2015-11-28,15889,F,ES,V,56,1995-01-16,0.0,249,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
8617992,2015-12-28,15889,F,ES,V,56,1995-01-16,0.0,250,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
9401570,2016-01-28,15889,F,ES,V,56,1995-01-16,0.0,251,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
10426092,2016-02-28,15889,F,ES,V,56,1995-01-16,0.0,252,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
11170871,2016-03-28,15889,F,ES,V,56,1995-01-16,0.0,253,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
12221013,2016-04-28,15889,F,ES,V,56,1995-01-16,0.0,254,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0.0,0.0,0
13026343,2016-05-28,15889,F,ES,V,56,1995-01-16,0.0,255,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,326124.90,01 - TOP,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0.0,0.0,0
416966,2015-01-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
836223,2015-02-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
1673960,2015-03-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
2092183,2015-04-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
3144383,2015-05-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
3565760,2015-06-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
4078995,2015-07-28,15890,A,ES,V,62,1995-01-16,0.0,246,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
5319233,2015-08-28,15890,A,ES,V,62,1995-01-16,0.0,247,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
5705187,2015-09-28,15890,A,ES,V,62,1995-01-16,0.0,248,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
6909778,2015-10-28,15890,A,ES,V,63,1995-01-16,0.0,249,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
7450450,2015-11-28,15890,A,ES,V,63,1995-01-16,0.0,250,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
8617993,2015-12-28,15890,A,ES,V,63,1995-01-16,0.0,251,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
9401569,2016-01-28,15890,A,ES,V,63,1995-01-16,0.0,252,1.0,NaN,1,A,S,N,N,KAT,N,1.0,28.0,MADRID,1.0,71461.20,02 - PARTICULARES,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8617839,2015-12-28,17042,N,ES,V,49,1995-05-23,0.0,203,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,251716.98,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
9401775,2016-01-28,17042,N,ES,V,49,1995-05-23,0.0,204,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,251716.98,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
10426298,2016-02-28,17042,N,ES,V,49,1995-05-23,0.0,205,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,251716.98,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
11171381,2016-03-28,17042,N,ES,V,49,1995-05-23,0.0,206,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,251716.98,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
12211716,2016-04-28,17042,N,ES,V,49,1995-05-23,0.0,207,1.0,NaN,1.0,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,251716.98,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13026852,2016-05-28,17042,N,ES,V,49,1995-05-23,0.0,208,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,251716.98,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
416859,2015-01-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
836340,2015-02-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
1674073,2015-03-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
2092296,2015-04-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
2933607,2015-05-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
3565667,2015-06-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
4079473,2015-07-28,17043,N,ES,V,67,2001-01-12,0.0,174,1.0,NaN,1.0,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
5319368,2015-08-28,17043,N,ES,V,67,2001-01-12,0.0,175,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
5705353,2015-09-28,17043,N,ES,V,67,2001-01-12,0.0,176,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
6909265,2015-10-28,17043,N,ES,V,67,2001-01-12,0.0,177,1.0,NaN,1.0,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
7449875,2015-11-28,17043,N,ES,V,67,2001-01-12,0.0,178,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
8617840,2015-12-28,17043,N,ES,V,67,2001-01-12,0.0,179,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
9401774,2016-01-28,17043,N,ES,V,67,2001-01-12,0.0,180,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
10426297,2016-02-28,17043,N,ES,V,68,2001-01-12,0.0,181,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
11171369,2016-03-28,17043,N,ES,V,68,2001-01-12,0.0,182,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
12211717,2016-04-28,17043,N,ES,V,68,2001-01-12,0.0,183,1.0,NaN,1.0,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
13026851,2016-05-28,17043,N,ES,V,68,2001-01-12,0.0,184,1.0,NaN,1,A,S,N,NaN,KAT,N,1.0,28.0,MADRID,1.0,183637.17,02 - PARTICULARES,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
4079472,2015-07-28,17044,N,ES,V,49,1995-05-09,0.0,242,1.0,NaN,1.0,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
5319367,2015-08-28,17044,N,ES,V,49,1995-05-09,0.0,243,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
5705333,2015-09-28,17044,N,ES,V,49,1995-05-09,0.0,244,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
6909266,2015-10-28,17044,N,ES,V,49,1995-05-09,0.0,245,1.0,NaN,1.0,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
7449874,2015-11-28,17044,N,ES,V,49,1995-05-09,0.0,246,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
8617841,2015-12-28,17044,N,ES,V,49,1995-05-09,0.0,247,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0
9401773,2016-01-28,17044,N,ES,V,49,1995-05-09,0.0,248,1.0,NaN,1,I,S,N,NaN,KAT,N,1.0,28.0,MADRID,0.0,49600.05,02 - PARTICULARES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0

In [103]:
filtered_sorted_data.to_csv('data_mining_latest.csv', index=False)

## Statistics

In [108]:
filtered_sorted_data.describe()

,Customer_Code,New_customer_Index,Primary,Primary_Addr,Province_code,Activity_index,Gross_income,Saving_Account,Guarantees,Current_Accounts,Derivada_Account,Payroll_Account,Junior_Account,Mas_particular_Account,particular_Account,Plus_Account,Shortterm_deposits,Mediumterm_deposits,Longterm_deposits,eaccount,Funds,Mortgage,Pensions,Loans,Taxes,Credit_Card,Securities,Home_Account,Payroll,Pensions,Direct_Debit
count,10000.000000,9988.000000,9988.000000,9988.0,9954.000000,9988.000000,9.017000e+03,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.0,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0000,10000.000000,9988.000000,9988.000000,10000.000000
mean,16425.027000,0.002503,1.127553,1.0,27.340968,0.700541,2.325542e+05,0.001700,0.001700,0.591800,0.00070,0.223300,0.0,0.003600,0.27380,0.156500,0.002300,0.005700,0.097700,0.229500,0.110700,0.047000,0.143600,0.026500,0.209600,0.260800,0.1696,0.019300,0.155787,0.180016,0.379800
std,358.059633,0.049970,3.533437,0.0,5.586138,0.458044,1.837271e+05,0.041198,0.041198,0.491525,0.02645,0.416479,0.0,0.059895,0.44593,0.363347,0.047906,0.075287,0.296923,0.420532,0.313776,0.211649,0.350701,0.160625,0.407043,0.439093,0.3753,0.137584,0.362671,0.384220,0.485361
min,15889.000000,0.000000,1.000000,1.0,1.000000,0.000000,3.166824e+04,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000
25%,16093.000000,0.000000,1.000000,1.0,28.000000,0.000000,1.319880e+05,0.000000,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000
50%,16426.000000,0.000000,1.000000,1.0,28.000000,1.000000,1.895294e+05,0.000000,0.000000,1.000000,0.00000,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000
75%,16739.000000,0.000000,1.000000,1.0,28.000000,1.000000,2.811405e+05,0.000000,0.000000,1.000000,0.00000,0.000000,0.0,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0000,0.000000,0.000000,0.000000,1.000000
max,17044.000000,1.000000,99.000000,1.0,49.000000,1.000000,2.202379e+06,1.000000,1.000000,1.000000,1.00000,1.000000,0.0,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000